motd:
  enabled: true
  allow-color: true
  messages:
  - Welcome to NovusCraft!
hat:
  enabled: true
  restricted-blocks: []
rank:
  enabled: true
  silent: false
garbage:
  ignored-worlds: []
  ignored-entities:
    - VILLAGER
    - OCELOT
    - WOLF
    - COW
    - SHEEP