name: NovusFundamentals
description: A collection of small plugins and tools used on NovusCraft.
version: 1.0.0
main: com.TeamNovus.NovusFundamentals.NovusFundamentals
commands:
  hat:
    description: Place a hat on your head!
  unhat:
    description: Remove a hat from your head!
  gcclear:
    aliases: gcc
    description: Check server Memory and usage!
  reloadnovus:
    description: Reload NovusFundamentals!